name: Tag Docker Image with Git

on:
  push:
    tags: 
      - '*'

env:
  REGISTRY: docker.io
  IMAGE_NAME: jeffscrum/coredns-blocker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set env
      run: |
        echo "BUILD_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

    - name: Login to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata for the Docker image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v5
      id: build
      with:
        context: .
        push: true
        build-args: BUILD_VERSION=v${{ env.BUILD_VERSION }}
        tags: ${{ steps.meta.outputs.tags }}
